version: '3'

services:
  redis:
      image: redis:6-alpine
      container_name: hotwired_ats_redis
      command: redis-server --appendonly yes
      volumes:
        - redis_data:/data
      ports:
        - "6379:6379"
      restart: unless-stopped


volumes:
  redis_data: