default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['HOST'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hotwired_ats_development
  username: <%= ENV['POSTGRES_USER'] %>

test:
  <<: *default
  database: hotwired_ats_test
  username: <%= ENV['POSTGRES_USER'] %>
production:
  <<: *default
  database: hotwired_ats_production
