default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV["host"] %>
  username: <%= ENV["username"] %>
  password: <%= ENV["password"] %>

development:
  <<: *default
  database: hotwired_ats_development

test:
  <<: *default
  database: hotwired_ats_test

production:
  <<: *default
  database: hotwired_ats_production
  username: hotwired_ats
  password: <%= ENV["HOTWIRED_ATS_DATABASE_PASSWORD"] %>
